export const DATA_TYPE = [
  {
    ID: '1',
    UF_ACTIVE: '1',
    UF_CHART_COLOR: '',
    UF_CREATE_DATE: '07.02.2022 15:26:45',
    UF_DESCRIPTION: 'Во глубине сибирских руд Храните гордое терпенье, Не пропадет ваш скорбный труд И дум высокое стремленье.',
    UF_IS_SCORED: '1',
    UF_NAME: 'тест',
    UF_POINTS: '100',
    UF_RELATED_TYPE: [],
    UF_SUM_RELATED: '0',
  },
  {
    ID: '2',
    UF_ACTIVE: '0',
    UF_CHART_COLOR: '',
    UF_CREATE_DATE: '01.08.2022 10:00:00',
    UF_DESCRIPTION: 'Что-то',
    UF_IS_SCORED: '0',
    UF_NAME: 'Валовый доход',
    UF_POINTS: '1',
    UF_RELATED_TYPE: [],
    UF_SUM_RELATED: '0',
  },
  {
    ID: '3',
    UF_ACTIVE: '0',
    UF_CHART_COLOR: '',
    UF_CREATE_DATE: '07.09.2022 02:10:11',
    UF_DESCRIPTION: '',
    UF_IS_SCORED: '0',
    UF_NAME: 'Евро',
    UF_POINTS: null,
    UF_RELATED_TYPE: ['1', '2'],
    UF_SUM_RELATED: '0',
  },
  {
    ID: '4',
    UF_ACTIVE: '1',
    UF_CHART_COLOR: '',
    UF_CREATE_DATE: '06.01.2023 00:00:00',
    UF_DESCRIPTION: '',
    UF_IS_SCORED: '0',
    UF_NAME: 'Какая-то статистика',
    UF_POINTS: null,
    UF_RELATED_TYPE: ['1'],
    UF_SUM_RELATED: '1',
  },
  {
    ID: '5',
    UF_ACTIVE: '0',
    UF_CHART_COLOR: '',
    UF_CREATE_DATE: '06.02.2023 10:53:11',
    UF_DESCRIPTION: '',
    UF_IS_SCORED: '1',
    UF_NAME: 'Сумма',
    UF_POINTS: '10000',
    UF_RELATED_TYPE: ['1'],
    UF_SUM_RELATED: '0',
  },
  {
    ID: '6',
    UF_ACTIVE: '1',
    UF_CHART_COLOR: '',
    UF_CREATE_DATE: '06.02.2023 9:54:00',
    UF_DESCRIPTION: 'Появление Маяковского в русском поэтическом обществе можно сравнить с эффектом разорвавшейся бомбы.',
    UF_IS_SCORED: '0',
    UF_NAME: 'Эмайлы',
    UF_POINTS: null,
    UF_RELATED_TYPE: ['1', '4', '5'],
    UF_SUM_RELATED: '1',
  },
  {
    ID: '7',
    UF_ACTIVE: '0',
    UF_CHART_COLOR: '',
    UF_CREATE_DATE: '07.02.2023 15:23:23',
    UF_DESCRIPTION: '',
    UF_IS_SCORED: '0',
    UF_NAME: 'Звонки',
    UF_POINTS: null,
    UF_RELATED_TYPE: ['1', '11', '12'],
    UF_SUM_RELATED: '0',
  },
  {
    ID: '8',
    UF_ACTIVE: '1',
    UF_CHART_COLOR: '',
    UF_CREATE_DATE: '01.11.2022 01:00:00',
    UF_DESCRIPTION: '',
    UF_IS_SCORED: '0',
    UF_NAME: 'Санкт-Петербург',
    UF_POINTS: null,
    UF_RELATED_TYPE: ['1'],
    UF_SUM_RELATED: '0',
  },
  {
    ID: '9',
    UF_ACTIVE: '0',
    UF_CHART_COLOR: '',
    UF_CREATE_DATE: '07.12.2023 12:12:12',
    UF_DESCRIPTION: 'Известно презрение Маяковского к буржуазному обществу. Оно еще больше усиливалось из-за вынужденного участия поэта в таких публичных чтениях. Стихотворение «Нате!»',
    UF_IS_SCORED: '1',
    UF_NAME: 'Москва округлина',
    UF_POINTS: '11111',
    UF_RELATED_TYPE: [],
    UF_SUM_RELATED: '0',
  },
  {
    ID: '10',
    UF_ACTIVE: '1',
    UF_CHART_COLOR: '',
    UF_CREATE_DATE: '20.02.2023 20:03:00',
    UF_DESCRIPTION: '',
    UF_IS_SCORED: '1',
    UF_NAME: 'Река далекая',
    UF_POINTS: '5959',
    UF_RELATED_TYPE: [],
    UF_SUM_RELATED: '0',
  },
  {
    ID: '11',
    UF_ACTIVE: '0',
    UF_CHART_COLOR: '',
    UF_CREATE_DATE: '29.02.2023 23:23:44',
    UF_DESCRIPTION: '',
    UF_IS_SCORED: '0',
    UF_NAME: 'Одиннадцатая статистика',
    UF_POINTS: '1000',
    UF_RELATED_TYPE: [],
    UF_SUM_RELATED: '0',
  },
  {
    ID: '1',
    UF_ACTIVE: '1',
    UF_CHART_COLOR: '',
    UF_CREATE_DATE: '01.03.2023 14:57:00',
    UF_DESCRIPTION: 'Главным же образом, которым Маяковский описывает толпу, является «стоглавая вошь».',
    UF_IS_SCORED: '0',
    UF_NAME: 'Виндовс экселевс',
    UF_POINTS: null,
    UF_RELATED_TYPE: [],
    UF_SUM_RELATED: '0',
  },
];

export const DATA_EMPLOYEE = [
  {
    ID: '1',
    UF_ACTIVE: '1',
    UF_CREATE_DATE: '01.01.2022 15:26:45',
    UF_DEPARTMENT_ID: '1',
    UF_EMPLOYEE_ID: '1',
    UF_INVERTED_CHART: '1',
    UF_NOT_SHOW_CHART: '1',
    UF_ONLY_FACT: '0',
    UF_PERIODICITY: '2',
    UF_SORT: null,
    UF_STATISTIC_TYPE: '1',
  },
  {
    ID: '2',
    UF_ACTIVE: '1',
    UF_CREATE_DATE: '20.02.2022 09:11:45',
    UF_DEPARTMENT_ID: '2',
    UF_EMPLOYEE_ID: '2',
    UF_INVERTED_CHART: '0',
    UF_NOT_SHOW_CHART: '1',
    UF_ONLY_FACT: '0',
    UF_PERIODICITY: '2',
    UF_SORT: null,
    UF_STATISTIC_TYPE: '2',
  },
  {
    ID: '3',
    UF_ACTIVE: '1',
    UF_CREATE_DATE: '05.03.2022 13:11:01',
    UF_DEPARTMENT_ID: '3',
    UF_EMPLOYEE_ID: '3',
    UF_INVERTED_CHART: '0',
    UF_NOT_SHOW_CHART: '0',
    UF_ONLY_FACT: '0',
    UF_PERIODICITY: '1',
    UF_SORT: null,
    UF_STATISTIC_TYPE: '3',
  },
  {
    ID: '4',
    UF_ACTIVE: '0',
    UF_CREATE_DATE: '23.03.2023 17:20:45',
    UF_DEPARTMENT_ID: '4',
    UF_EMPLOYEE_ID: '4',
    UF_INVERTED_CHART: '0',
    UF_NOT_SHOW_CHART: '0',
    UF_ONLY_FACT: '0',
    UF_PERIODICITY: '3',
    UF_SORT: null,
    UF_STATISTIC_TYPE: '3',
  },
  {
    ID: '5',
    UF_ACTIVE: '1',
    UF_CREATE_DATE: '15.04.2022 02:29:46',
    UF_DEPARTMENT_ID: '4',
    UF_EMPLOYEE_ID: '5',
    UF_INVERTED_CHART: '1',
    UF_NOT_SHOW_CHART: '0',
    UF_ONLY_FACT: '0',
    UF_PERIODICITY: '2',
    UF_SORT: null,
    UF_STATISTIC_TYPE: '11',
  },
  {
    ID: '6',
    UF_ACTIVE: '1',
    UF_CREATE_DATE: '29.05.2022 12:12:12',
    UF_DEPARTMENT_ID: '5',
    UF_EMPLOYEE_ID: '6',
    UF_INVERTED_CHART: '0',
    UF_NOT_SHOW_CHART: '0',
    UF_ONLY_FACT: '0',
    UF_PERIODICITY: '2',
    UF_SORT: null,
    UF_STATISTIC_TYPE: '6',
  },
  {
    ID: '7',
    UF_ACTIVE: '1',
    UF_CREATE_DATE: '07.06.2022 18:23:45',
    UF_DEPARTMENT_ID: '6',
    UF_EMPLOYEE_ID: '7',
    UF_INVERTED_CHART: '1',
    UF_NOT_SHOW_CHART: '1',
    UF_ONLY_FACT: '0',
    UF_PERIODICITY: '',
    UF_SORT: null,
    UF_STATISTIC_TYPE: '8',
  },
  {
    ID: '8',
    UF_ACTIVE: '0',
    UF_CREATE_DATE: '19.07.2022 12:26:45',
    UF_DEPARTMENT_ID: '7',
    UF_EMPLOYEE_ID: '1',
    UF_INVERTED_CHART: '0',
    UF_NOT_SHOW_CHART: '1',
    UF_ONLY_FACT: '0',
    UF_PERIODICITY: '3',
    UF_SORT: null,
    UF_STATISTIC_TYPE: '5',
  },
  {
    ID: '9',
    UF_ACTIVE: '1',
    UF_CREATE_DATE: '23.09.2022 08:17:45',
    UF_DEPARTMENT_ID: '8',
    UF_EMPLOYEE_ID: '8',
    UF_INVERTED_CHART: '0',
    UF_NOT_SHOW_CHART: '0',
    UF_ONLY_FACT: '1',
    UF_PERIODICITY: '2',
    UF_SORT: null,
    UF_STATISTIC_TYPE: '3',
  },
  {
    ID: '10',
    UF_ACTIVE: '0',
    UF_CREATE_DATE: '10.02.2023 07:26:45',
    UF_DEPARTMENT_ID: '248',
    UF_EMPLOYEE_ID: '9',
    UF_INVERTED_CHART: '0',
    UF_NOT_SHOW_CHART: '0',
    UF_ONLY_FACT: '1',
    UF_PERIODICITY: '2',
    UF_SORT: null,
    UF_STATISTIC_TYPE: '9',
  },
  {
    ID: '11',
    UF_ACTIVE: '1',
    UF_CREATE_DATE: '15.02.2023 21:20:45',
    UF_DEPARTMENT_ID: '2',
    UF_EMPLOYEE_ID: '4',
    UF_INVERTED_CHART: '0',
    UF_NOT_SHOW_CHART: '1',
    UF_ONLY_FACT: '1',
    UF_PERIODICITY: '1',
    UF_SORT: null,
    UF_STATISTIC_TYPE: '1',
  },
  {
    ID: '12',
    UF_ACTIVE: '1',
    UF_CREATE_DATE: '01.03.2023 12:00:00',
    UF_DEPARTMENT_ID: '10',
    UF_EMPLOYEE_ID: '4',
    UF_INVERTED_CHART: '0',
    UF_NOT_SHOW_CHART: '1',
    UF_ONLY_FACT: '0',
    UF_PERIODICITY: '1',
    UF_SORT: null,
    UF_STATISTIC_TYPE: '4',
  },
];

export const DATA_DEPARTMENTS = [
  { ID: '1', NAME: 'Владельцы', PARENT: '' },
  { ID: '2', NAME: 'IT Департамент CIO', PARENT: '' },
  { ID: '3', NAME: 'Разработка и внедрение', PARENT: 'IT Департамент CIO' },
  { ID: '4', NAME: 'Проекты', PARENT: 'IT Департамент CIO' },
  { ID: '5', NAME: 'Юридический департамент', PARENT: '' },
  { ID: '6', NAME: 'Недвижимость', PARENT: 'Юридический департамент' },
  { ID: '7', NAME: 'Финансовый отдел', PARENT: 'Юридический департамент' },
  { ID: '8', NAME: 'Финансовый менеджер', PARENT: 'Бюджетирование' },
  { ID: '9', NAME: 'Кадровый департамент', PARENT: '' },
  { ID: '10', NAME: 'Кадры CIO', PARENT: 'Кадровый департамент' },
];

export const DATA_USERS = [
  { ID: '1', NAME: 'Астапов Вадим Андреевич', IMG_URL: '../images/foto.png' },
  { ID: '2', NAME: 'Травникова Светлана Анатольевна', IMG_URL: null },
  { ID: '3', NAME: 'Белова Ольга Викторовна', IMG_URL: '../images/foto.png' },
  { ID: '4', NAME: 'Крамар Алексей Викторович', IMG_URL: null },
  { ID: '5', NAME: 'Житарюк Ольга Федоровна', IMG_URL: '../images/foto.png' },
  { ID: '6', NAME: 'Пономарев Дмитрий Анатольевич', IMG_URL: '../images/foto.png' },
  { ID: '7', NAME: 'Зевс повелитель молний', IMG_URL: null },
  { ID: '8', NAME: 'Виктор Тор', IMG_URL: '../images/foto.png' },
  { ID: '9', NAME: 'Гостенко Ксения Сергеевна', IMG_URL: null },
  { ID: '10', NAME: 'Биккель Елизавета Михайловна', IMG_URL: '../images/foto.png' },
];

export const DATA_PERIODS = [
  {ID: '1', NAME: 'День'},
  {ID: '2', NAME: 'Неделя'},
  {ID: '3', NAME: 'Месяц'},
]